# Generated by Django 5.2.7 on 2025-10-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat_number', models.IntegerField()),
                ('ayat_text', models.TextField(blank=True, null=True)),
                ('meaning_text', models.TextField(blank=True, null=True)),
                ('word_meaning', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('surah_name_arabic', models.CharField(max_length=200)),
                ('surah_name_malayalam', models.CharField(blank=True, max_length=200, null=True)),
                ('surah_name_english', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fraction_ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat_fraction_number', models.IntegerField()),
                ('ayat_fraction_text', models.TextField(blank=True, null=True)),
                ('ayat_fraction_meaning', models.TextField(blank=True, null=True)),
                ('ayat_fraction_tafseer', models.TextField(blank=True, null=True)),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.ayat')),
            ],
        ),
        migrations.AddField(
            model_name='ayat',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuser.surah'),
        ),
    ]
